### ISSUE TITLE
Can the pocketnc 1 be upgraded to use this software?

### ISSUE THREAD

**Issue by zakhenry** [PocketNC/pocketnc#1]
We have a version 1 pocket nc and would like to install rockhopper, but seeing this repo gives me hope we might be able to get the pocketnc-ui too if we upgraded. Is this possible, or are there hardware limitations?

**Comment by jallwine** [comment]
Yes, it's possible, but it's not officially supported and it will be tricky to get everything set up right. Development of Rockhopper and the UI started on the v1, but since the v2 replaces the v1 efforts were focused there. There are some features in the UI that won't work on the v1 because of missing hardware (specifically the Measure Tool buttons, as there is no tool probe). The trickiest part, though, is going to be converting the Settings repository to work with the v1 as a number of hardware pins changed functionality (a pin that was controlling the X axis, may now be controlling the Y axis, etc.). 

There is an upgrade option for the v1, which includes all hardware changes and the updated UI. You can take a look at that option [here](http://www.pocketnc.com/v1-accessories/v1-to-v2-upgrade).

If you'd prefer to stick with the v1, you might consider taking a look at this [blog post of mine](https://www.allwinedesigns.com/blog/pocketnc-jog-wheel), which explains how to load an old version of the software onto the v1. If you go that route, I'd recommend getting a second Beaglebone Black to ensure you have an easy way to get back to your current image which has all your calibration settings on it and software that is known to work. I worked with the image in my blog post for months, so it does work, but it will be missing some features, bugs fixes and design changes.

**Comment by jallwine** [comment]
The V1 has been officially supported for a while now. Our latest software, Kinetic Control, can be purchased here on a microSD card which can be inserted into the V1 and you'll be up and running!
